sudo: false
language: python

python:
  - "3.5"
  - "3.7"
  - "3.4"
  - "3.3"
  - "2.7"
  - pypy

env:
  - DJANGO="django==1.10.6"
  - DJANGO="django==1.9.12"
  - DJANGO="django==1.8.17"
  - DJANGO="django==3.0"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W uuslug; fi

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.10.6"
    - python: "3.3"
      env: DJANGO="django==1.9.12"
    - python: "3.7"
      env: DJANGO="django==3.0"
    - python: "3.7"
      env: DJANGO="django==3.0"

script: coverage run --source=uuslug manage.py test

after_success: coveralls
